apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-auth
  namespace: keda-demo
type: Opaque
stringData:
  host: amqp://demo:demo@rabbitmq.keda-demo.svc.cluster.local:5672/%2F
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: keda-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - name: amqp
              containerPort: 5672
            - name: mgmt
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-auth
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-auth
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: keda-demo
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: mgmt
      port: 15672
      targetPort: 15672

