apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deploy 
spec:
  replicas: 1
  selector:
    matchLabels:
        app: hello-world
  template:
    metadata:
      labels: 
        app: hello-world
    spec:
      imagePullSecrets:
        - name: docker-creds
      containers:
      - name: hello-world-container 
        image: gauris17/hello-world:v1 
        ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service 
metadata: 
  name: hello-world-service 
spec:
  selector: 
    app: hello-world 
  type: LoadBalancer
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 5000